### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by EssKayz** [jompero/unit_pathfinder_tira#1]
Time of repository download : 02/12/2019 18:53 GMT +2

So first of all - I was unable to actually run the programme through NetBeans, nor through any command line commands, and since there was no Jar compiled program either, I couldn't get any tests done, or validate that anything actually works.
I'm sure this is probably just my stupidity (?), but I even asked another student to help me out to configure 
the project so it would run for me, but to no luck.
Future thought - perhaps some kind of an instruction on how to run the program, or the tests would be a 
nice-to-have?

On top of that, there's a lot of .DS_Store files scattered around the entire project. Didn't sound like
anything usually found in Java codes, and sure enough Google responds with 'Mac Detected'. GitIgnore?
Not really relevant, but had me confused for a few minutes, as I was attempting to open them up to see if they had anything to do with the program itself.

Code style wise, otherwise looks pretty nice and readable, although there were some inconsistencies on the use of brackets on If statements. Sometimes you would use brackets, and sometimes not. Consistency in these would make the code more readable. 
I noticed you would leave the brackets away in situations where there was just  one line after the if statement - but then in other places you wouldn't line change in these situations, so that felt sort of incosistent at times. Using one style throughout the project would make it easier on the eyes to read, and subjectively even make it look prettier.
Example of the different ways if statements are written :

	case1
	if(x ..) {
		if(y ..)
			do things
		do other things
	}

	case2
	if(x ..) do things

	case 3 
	if(x ..){
		do things
	}
	
	
I noticed you had already started an placeholder for an implementation of PriorityQues. I imagine you're going to do the same for ArrayLists aswell eventually?

Also noticed a couple of places where submethods of the Array class were used, these should be pretty easy to replace with your own methods, so that could be a nice short-project for an lonely night with nothing better  to do.

All in all, I think the level of commentation was good where it was found (still a couple of classes without javadoc, but those were pretty self-explanatory anyways..), and gave a good idea of what the methods were supposed to do, even though I couldn't test them myself in any way.
Readability asides from the if statement brackets was also good, and there seemed to be a good amount of tests written, and on a surface level they also seem to cover quite a lot of the project.

**Comment by jompero** [comment]
Hey! 

Thanks for the feedback!

Sorry about not explicitly mentioning it but it is an Eclipse project as opposed to NetBeans. So I assume one would need to open it in Eclipse, of course there might be a way to open it in NetBeans.

.DS_Store is now removed and ignored. Am working on MAC so just generally thought they were part of Eclipse. :D

Got some similar comments about the code quality from a colleague so will address that as well.

**Comment by jompero** [comment]
Al if clauses are now consistent too. Closing issue 👍
