### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by PyryV** [jompero/unit_pathfinder_tira#2]
# Vertaisarviointi
Projekti ladattu 22.02. klo 18.00

Sovellus näyttää yleisesti todella hyvältä. Koodin seassa on reilusti kommentointia ja javadocien määrä on suuri, mikä helpotti koodin ymmärtämistä huomattavasti. Koodissa ei siis ainakaan omaan silmääni osunut mitään korjattavaa. Ohjelman käynnistyksen kanssa minulla oli kuitenkin hieman vaikeuksia, sillä gradle run -komento ei toiminut, mutta pienen tutkimisen jälkeen selvisi, että build.gradle-tiedostosta puuttuivat rivit:

```java
apply plugin: 'application'
mainClassName = 'unit_pathfinder_tira.Main'
```

Kyseiset rivit lisättyäni sain ohjelman aukeamaan. 

## Käyttöliittymä
Käyttöliittymä oli hyvän näköinen, mutta olisin ehkä toivonut siihen jonkin pienen tekstinpätkän kertomaan miten ohjelmaa käytetään. Lopulta eri asioita klikkailtuani tajusin mistä on kyse. Sitten kun ohjelmaa oppi käyttämään oli sen käyttö yksinkertaista ja nopeaa. Erityisesti pidin siitä miten eri reitinhaku algoritmit oli kuvattu graafisesti ja kuinka niitä pystyi vain klikkailemaan joko näkyväksi tai näkymättömäksi. Kokonaisuudessaan käyttöliittymä on selkeä ja siitä näkee kaikki tehokkuusvertailuun tarvittavat tiedot helposti. 

Toiminnaltaan sovellus on erittäin hyvä ja ainoat parannettavat asiat olivat loppuen lopuksi pieniä yksityiskohtia käyttöliittymän osalta, mitkä eivät sinänsä vaikuta sovelluksen tehokkuuteen tai muihin tärkeisiin osa-alueisiin.

**Comment by jompero** [comment]
Jes! Kiitti kommenteista. Eclipse ei jostain syystä herjaa mitään, mutta build.gradle on nyt päivitetty. Myös käyttöliittymä on päivitetty palautteen mukaisesti. 👍
